spring:
  application:
    name: eurekaserver
server:
  port: ${SERVER_PORT}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}